spring.application.name=BackEnd_Locator

spring.datasource.url=jdbc:mariadb://172.16.74.130:3306/gta
spring.datasource.username=root
spring.datasource.password=Jn123*

logging.level.org.springframework.web=DEBUG
logging.level.com.fdsa.altairis=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

server.port=8080