spring.application.name=BackEnd_Locator

spring.datasource.url=jdbc:mariadb://44.222.218.201:3306/gta
spring.datasource.username=root
spring.datasource.password=Rootgta2026!

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.web=DEBUG
logging.level.com.fdsa.altairis=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

server.port=8080